// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticlesItem: typeof import('./src/components/articles/ArticlesItem.vue')['default']
    ArticlesWrapper: typeof import('./src/components/articles/ArticlesWrapper.vue')['default']
    DetailItem: typeof import('./src/components/detail/DetailItem.vue')['default']
    DetailWrapper: typeof import('./src/components/detail/DetailWrapper.vue')['default']
    FooterItem: typeof import('./src/components/footer/FooterItem.vue')['default']
    HeaderLayout: typeof import('./src/components/hearder/HeaderLayout.vue')['default']
    HeaderLogo: typeof import('./src/components/hearder/headerItem/headerLogo.vue')['default']
    HeaderMenu: typeof import('./src/components/hearder/headerItem/headerMenu.vue')['default']
    HeaderSearch: typeof import('./src/components/hearder/headerItem/headerSearch.vue')['default']
    HeaderWrapper: typeof import('./src/components/hearder/headerWrapper/HeaderWrapper.vue')['default']
    MiddleItem: typeof import('./src/components/middle/MiddleItem.vue')['default']
    MiddleWrapper: typeof import('./src/components/middle/MiddleWrapper.vue')['default']
    NavBar: typeof import('./src/components/navBar/NavBar.vue')['default']
    PubAdsense: typeof import('./src/components/pub/pubAdsense/PubAdsense.vue')['default']
    PubError: typeof import('./src/components/pub/pubError/PubError.vue')['default']
    PubImage: typeof import('./src/components/pub/pubImage/PubImage.vue')['default']
    PubLoading: typeof import('./src/components/pub/pubLoading/PubLoading.vue')['default']
    PubLogo: typeof import('./src/components/pub/pubLogo/pubLogo.vue')['default']
    PubMenu: typeof import('./src/components/pub/pubMenu/PubMenu.vue')['default']
    PubMenuItem: typeof import('./src/components/pub/pubMenu/PubMenuItem.vue')['default']
    PubMenuItemChild: typeof import('./src/components/pub/pubMenu/PubMenuItemChild.vue')['default']
    PubNav: typeof import('./src/components/pub/pubNav/PubNav.vue')['default']
    PubNews: typeof import('./src/components/pub/pubNews/PubNews.vue')['default']
    PubPagination: typeof import('./src/components/pub/pubPagination/PubPagination.vue')['default']
    PubSearch: typeof import('./src/components/pub/pubSearch/PubSearch.vue')['default']
    PubTop: typeof import('./src/components/pub/pubTop/PubTop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanIcon: typeof import('vant/es')['Icon']
    VanPagination: typeof import('vant/es')['Pagination']
  }
}
